"""
Email Templates

Pre-designed HTML email templates for various notifications.
"""

from typing import Dict, Any
from datetime import datetime


class EmailTemplates:
    """HTML email templates for financial notifications"""

    @staticmethod
    def base_template(title: str, content: str) -> str:
        """Base HTML email template"""
        return f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            color: #2c3e50;
            font-size: 24px;
        }}
        .content {{
            color: #555;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            text-align: center;
            font-size: 12px;
            color: #999;
        }}
        .button {{
            display: inline-block;
            padding: 12px 24px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            margin: 10px 0;
        }}
        .alert {{
            padding: 15px;
            border-radius: 4px;
            margin: 15px 0;
        }}
        .alert-success {{
            background-color: #d4edda;
            border-left: 4px solid #28a745;
            color: #155724;
        }}
        .alert-warning {{
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            color: #856404;
        }}
        .alert-info {{
            background-color: #d1ecf1;
            border-left: 4px solid #17a2b8;
            color: #0c5460;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #f8f9fa;
            font-weight: 600;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{title}</h1>
        </div>
        <div class="content">
            {content}
        </div>
        <div class="footer">
            <p>Generated by your Financial Assistant</p>
            <p>{datetime.now().strftime("%B %d, %Y at %I:%M %p")}</p>
            <p style="margin-top: 10px;">
                <small>This is an automated email. Please do not reply.</small>
            </p>
        </div>
    </div>
</body>
</html>
"""

    @staticmethod
    def trade_confirmation(trade_data: Dict[str, Any]) -> str:
        """Trade execution confirmation email"""
        content = f"""
        <div class="alert alert-success">
            <h2 style="margin-top: 0;">✅ Trade Executed Successfully</h2>
        </div>

        <h3>Order Details</h3>
        <table>
            <tr>
                <th>Order ID</th>
                <td><code>{trade_data.get('order_id', 'N/A')}</code></td>
            </tr>
            <tr>
                <th>Symbol</th>
                <td><strong>{trade_data.get('symbol', 'N/A')}</strong></td>
            </tr>
            <tr>
                <th>Action</th>
                <td>{trade_data.get('side', 'N/A').upper()}</td>
            </tr>
            <tr>
                <th>Shares</th>
                <td>{trade_data.get('filled_qty', 0):.4f}</td>
            </tr>
            <tr>
                <th>Average Price</th>
                <td>${trade_data.get('filled_avg_price', 0):.2f}</td>
            </tr>
            <tr>
                <th>Total Amount</th>
                <td><strong>${trade_data.get('total_amount', 0):,.2f}</strong></td>
            </tr>
            <tr>
                <th>Status</th>
                <td><span style="color: #28a745;">●</span> {trade_data.get('status', 'N/A').upper()}</td>
            </tr>
        </table>

        <div class="alert alert-info">
            <p><strong>What happens next?</strong></p>
            <p>Your trade has been executed in your paper trading account. You can view your portfolio anytime by asking your Financial Assistant.</p>
        </div>

        <p style="text-align: center; margin-top: 30px;">
            <a href="#" class="button">View Portfolio</a>
        </p>
        """
        return EmailTemplates.base_template("Trade Confirmation", content)

    @staticmethod
    def budget_summary(budget_data: Dict[str, Any]) -> str:
        """Monthly budget summary email"""
        content = f"""
        <h2>Your Monthly Budget Summary</h2>

        <div class="alert alert-info">
            <p><strong>Month:</strong> {budget_data.get('month', 'Current Month')}</p>
            <p><strong>Income:</strong> ${budget_data.get('total_income', 0):,.2f}</p>
        </div>

        <h3>Spending Breakdown (50/30/20 Rule)</h3>
        <table>
            <tr>
                <th>Category</th>
                <th>Budgeted</th>
                <th>Spent</th>
                <th>Remaining</th>
                <th>Status</th>
            </tr>
            <tr>
                <td><strong>NEEDS (50%)</strong></td>
                <td>${budget_data.get('needs_budget', 0):,.2f}</td>
                <td>${budget_data.get('needs_spent', 0):,.2f}</td>
                <td>${budget_data.get('needs_remaining', 0):,.2f}</td>
                <td>{EmailTemplates._status_indicator(budget_data.get('needs_percent', 0))}</td>
            </tr>
            <tr>
                <td><strong>WANTS (30%)</strong></td>
                <td>${budget_data.get('wants_budget', 0):,.2f}</td>
                <td>${budget_data.get('wants_spent', 0):,.2f}</td>
                <td>${budget_data.get('wants_remaining', 0):,.2f}</td>
                <td>{EmailTemplates._status_indicator(budget_data.get('wants_percent', 0))}</td>
            </tr>
            <tr>
                <td><strong>SAVINGS (20%)</strong></td>
                <td>${budget_data.get('savings_budget', 0):,.2f}</td>
                <td>${budget_data.get('savings_spent', 0):,.2f}</td>
                <td>${budget_data.get('savings_remaining', 0):,.2f}</td>
                <td>{EmailTemplates._status_indicator(budget_data.get('savings_percent', 0))}</td>
            </tr>
        </table>

        <h3>Savings Goals Progress</h3>
        {EmailTemplates._render_goals(budget_data.get('goals', []))}

        <div class="alert alert-success" style="margin-top: 30px;">
            <p><strong>Great job!</strong> Keep tracking your spending to stay on budget.</p>
        </div>
        """
        return EmailTemplates.base_template("Monthly Budget Summary", content)

    @staticmethod
    def weekly_spending_report(spending_data: Dict[str, Any]) -> str:
        """Weekly spending report email"""
        content = f"""
        <h2>Your Weekly Spending Report</h2>

        <div class="alert alert-info">
            <p><strong>Week of:</strong> {spending_data.get('week_start', 'N/A')} - {spending_data.get('week_end', 'N/A')}</p>
            <p><strong>Total Spent:</strong> ${spending_data.get('total_spent', 0):,.2f}</p>
        </div>

        <h3>Top Spending Categories</h3>
        <table>
            <tr>
                <th>Category</th>
                <th>Amount</th>
                <th>% of Total</th>
            </tr>
            {EmailTemplates._render_spending_categories(spending_data.get('categories', []))}
        </table>

        <h3>Notable Transactions</h3>
        <table>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Amount</th>
            </tr>
            {EmailTemplates._render_transactions(spending_data.get('notable_transactions', []))}
        </table>

        <div class="alert alert-warning">
            <p><strong>Budget Alert:</strong> {spending_data.get('alert_message', 'You\'re on track!')}</p>
        </div>
        """
        return EmailTemplates.base_template("Weekly Spending Report", content)

    @staticmethod
    def investment_alert(alert_data: Dict[str, Any]) -> str:
        """Investment performance alert email"""
        alert_type = alert_data.get('type', 'info')
        alert_class = f"alert-{alert_type}"

        content = f"""
        <div class="alert {alert_class}">
            <h2 style="margin-top: 0;">{alert_data.get('title', 'Investment Update')}</h2>
        </div>

        <p>{alert_data.get('message', 'No message provided.')}</p>

        <h3>Portfolio Summary</h3>
        <table>
            <tr>
                <th>Metric</th>
                <th>Value</th>
            </tr>
            <tr>
                <td>Total Value</td>
                <td><strong>${alert_data.get('portfolio_value', 0):,.2f}</strong></td>
            </tr>
            <tr>
                <td>Total Invested</td>
                <td>${alert_data.get('total_invested', 0):,.2f}</td>
            </tr>
            <tr>
                <td>Gain/Loss</td>
                <td style="color: {EmailTemplates._gain_loss_color(alert_data.get('gain_loss', 0))};">
                    {EmailTemplates._format_gain_loss(alert_data.get('gain_loss', 0))}
                </td>
            </tr>
            <tr>
                <td>Return (%)</td>
                <td style="color: {EmailTemplates._gain_loss_color(alert_data.get('return_percent', 0))};">
                    {alert_data.get('return_percent', 0):.2f}%
                </td>
            </tr>
        </table>

        {alert_data.get('additional_content', '')}
        """
        return EmailTemplates.base_template(alert_data.get('title', 'Investment Alert'), content)

    # Helper methods
    @staticmethod
    def _status_indicator(percent: float) -> str:
        """Generate status indicator based on spending percentage"""
        if percent < 80:
            return '<span style="color: #28a745;">● On Track</span>'
        elif percent < 100:
            return '<span style="color: #ffc107;">● Watch Out</span>'
        else:
            return '<span style="color: #dc3545;">● Over Budget</span>'

    @staticmethod
    def _render_goals(goals: list) -> str:
        """Render savings goals as HTML"""
        if not goals:
            return "<p>No savings goals set yet.</p>"

        html = "<table>"
        for goal in goals:
            progress = (goal.get('current', 0) / goal.get('target', 1)) * 100
            html += f"""
            <tr>
                <td><strong>{goal.get('name', 'Goal')}</strong></td>
                <td>${goal.get('current', 0):,.2f} / ${goal.get('target', 0):,.2f}</td>
                <td>{progress:.1f}%</td>
            </tr>
            """
        html += "</table>"
        return html

    @staticmethod
    def _render_spending_categories(categories: list) -> str:
        """Render spending categories as table rows"""
        if not categories:
            return "<tr><td colspan='3'>No spending data</td></tr>"

        html = ""
        for cat in categories:
            html += f"""
            <tr>
                <td>{cat.get('name', 'Unknown')}</td>
                <td>${cat.get('amount', 0):,.2f}</td>
                <td>{cat.get('percent', 0):.1f}%</td>
            </tr>
            """
        return html

    @staticmethod
    def _render_transactions(transactions: list) -> str:
        """Render transactions as table rows"""
        if not transactions:
            return "<tr><td colspan='3'>No notable transactions</td></tr>"

        html = ""
        for txn in transactions:
            html += f"""
            <tr>
                <td>{txn.get('date', 'N/A')}</td>
                <td>{txn.get('description', 'N/A')}</td>
                <td>${txn.get('amount', 0):,.2f}</td>
            </tr>
            """
        return html

    @staticmethod
    def _gain_loss_color(value: float) -> str:
        """Return color for gain/loss values"""
        return "#28a745" if value >= 0 else "#dc3545"

    @staticmethod
    def _format_gain_loss(value: float) -> str:
        """Format gain/loss with sign"""
        sign = "+" if value >= 0 else ""
        return f"{sign}${value:,.2f}"
